services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-signal-desk
    restart: unless-stopped
    ports:
      - "8000:80"  # откроешь 8080 или повесим на реверс-прокси позже
